project_id = "tlvjvlogyirfatfoujrv"

[functions.cron-trigger-schedule-worker]
verify_jwt = false

[functions.schedule-worker]
verify_jwt = false

[functions.getlate-connect]
verify_jwt = true

[functions.getlate-post]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false
